server:
  port: 8080
spring:
  application:
    name: quartz
  quartz:
    job-store-type: JDBC
    jdbc:
      initialize-schema: NEVER
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            dataSource: myDS
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
          dataSource:
            myDS:
              provider: hikaricp
              driver: org.postgresql.Driver
              URL: jdbc:postgresql://127.0.0.1:5432/quartz
              user: postgres
              password: postgres
              maxConnections: 5
